vich_uploader:
  db_driver: orm

  mappings:
    tricksImage:
      uri_prefix: /img/tricksImage
      upload_destination: "%kernel.project_dir%/public/img/tricksImage"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
    featuredImage:
      uri_prefix: /img/tricksImage
      upload_destination: "%kernel.project_dir%/public/img/tricksImage"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
